on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "BAR" > test.txt
      - uses: actions/upload-artifact@v4.4.3
        with:
          name: test
          path: test.txt
